-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/IlarosNote/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("IlarosNote", "esES") or LibStub("AceLocale-3.0"):NewLocale("IlarosNote", "esMX")
if not L then return end

-- L["Add Handy Note"] = "Add Handy Note"
-- L["Add this location to Cartographer_Waypoints"] = "Add this location to Cartographer_Waypoints"
-- L["Add this location to IlarosNavi waypoints"] = "Add this location to IlarosNavi waypoints"
--[==[ L[ [=[
Alt+Right Click To Add a IlarosNote]=] ] = [=[
Alt+Right Click To Add a IlarosNote]=] ]==]
-- L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"
-- L["Configuration for each individual plugin database."] = "Configuration for each individual plugin database."
-- L["Delete Handy Note"] = "Delete Handy Note"
-- L["Description/Notes:"] = "Description/Notes:"
-- L["Edit Handy Note"] = "Edit Handy Note"
-- L["Enable IlarosNote"] = "Enable IlarosNote"
-- L["Enable or disable IlarosNote"] = "Enable or disable IlarosNote"
-- L["ERROR_CREATE_NOTE1"] = "IlarosNote cannot create a note here as it is unable to obtain your current location. Usually this is because there is no map for the zone you are in."
-- L["IlarosNote"] = "IlarosNote"
-- L["Icon Alpha"] = "Icon Alpha"
-- L["Icon Scale"] = "Icon Scale"
-- L["Minimap Icon Alpha"] = "Minimap Icon Alpha"
-- L["Minimap Icon Scale"] = "Minimap Icon Scale"
-- L["(No Title)"] = "(No Title)"
-- L["Overall settings"] = "Overall settings"
-- L["Overall settings that affect every database"] = "Overall settings that affect every database"
-- L["Plugin databases"] = "Plugin databases"
-- L["Plugins"] = "Plugins"
-- L["Portal"] = "Portal"
-- L["Show on continent map"] = "Show on continent map"
-- L["Show the following plugins on the map"] = "Show the following plugins on the map"
-- L["Syntax:"] = "Syntax:"
-- L["The alpha transparency of the icons"] = "The alpha transparency of the icons"
-- L["The overall alpha transparency of the icons on the Minimap"] = "The overall alpha transparency of the icons on the Minimap"
-- L["The overall alpha transparency of the icons on the World Map"] = "The overall alpha transparency of the icons on the World Map"
-- L["The overall scale of the icons on the Minimap"] = "The overall scale of the icons on the Minimap"
-- L["The overall scale of the icons on the World Map"] = "The overall scale of the icons on the World Map"
-- L["The scale of the icons"] = "The scale of the icons"
-- L["These settings control the look and feel of IlarosNote globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "These settings control the look and feel of IlarosNote globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."
-- L["These settings control the look and feel of the IlarosNote icons."] = "These settings control the look and feel of the IlarosNote icons."
-- L["Title"] = "Title"
-- L["World Map Icon Alpha"] = "World Map Icon Alpha"
-- L["World Map Icon Scale"] = "World Map Icon Scale"

